[package]
name = "stderred"
version = "0.1.0"
authors = ["Replit"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = { version = "3.1", features = ["derive"] }
itertools = "0.10"
memmap = "0.7"
nix = "0.23"
xmas-elf = "0.8"
